version: '3.8'

services:
    frontend:
      image: frontapp:latest
      command: sh -c "sleep 30s ; python3 ./main.py"
      ports:
        - "8000:8000"
      depends_on:
        - mysql
        
    mysql:
      image: back2:latest
      environment:
        MYSQL_DATABASE: 'employees'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - "3306:3306"
