apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: js724415/myimagesnode:v4
        command: ["sh", "-c", "sleep 30s && python3 ./main.py"]  
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_HOST
          value: "mysql-service"  
