# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: js724415/myimagesnode:v2
        ports:
        - containerPort: 8000
        env:
        - name: BACKEND_HOST
          value: "mysql-service"  # Set backend service name here

---

# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---

# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: js724415/myimagesnode:v3  # Assuming v2 is your MySQL backend image
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_ROOT_PASSWORD
          value: root

---

# mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
