---

# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: js724415/myimagesnode:v3
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_ROOT_PASSWORD
          value: root

